id: 1917754f-53d3-48fd-ab47-a4a6767a3513
name: Account Service - Prod
values:
  - key: baseUrl
    value: 'http://accounts-api.accounts.svc.cluster.local:3002'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 0
_postman_exported_at: '2026-02-17T22:41:58.063Z'
_postman_exported_using: Postman/11.0.0
