id: e643955a-c8e5-40c7-a728-d9742e44e8ce
name: Account Service - Dev
values:
  - key: baseUrl
    value: 'http://localhost:3002'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 120
